# Generated by Django 2.0.5 on 2018-07-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='grades',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
